name: CD

on:
  push:
    branches:
      - react

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm test
      env:
        CI: true
    - name: Deploy to Github Pages
      run: npm run deploy -- -r https://${{github.token}}@github.com/${{github.repository}}.git
